//! Vendor constraint file generators.
//!
//! Output is deterministic byte for byte: ports are sorted (bus bits numerically),
//! nothing time- or machine-dependent is written, and lines end in `\n`.
//!
//! Differential ports: on XDC targets a manifest port `x` with a differential IO
//! standard constrains the HDL ports `x_p` and `x_n`. On iCE40 (PCF) the single HDL
//! port `x` (the `PACKAGE_PIN` of an `SB_IO`) is placed on the P leg.

use std::cmp::Ordering;
use std::fmt::Write as _;

use bitstream_boards::{ConstraintFormat, Target};
use bitstream_manifest::{Manifest, Pull, Slew, split_port_index};
use bitstream_rules::ResolvedPort;

/// A generated constraint file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Generated {
    /// File name, for example `blinky.xdc`.
    pub file_name: String,
    pub contents: String,
}

/// Generate the constraint file for the target's toolchain.
///
/// `ports` must come from a [`bitstream_rules::check`] report without errors.
pub fn generate(manifest: &Manifest, target: Target<'_>, ports: &[ResolvedPort]) -> Generated {
    let mut ports: Vec<&ResolvedPort> = ports.iter().collect();
    ports.sort_by(|a, b| port_order(&a.port, &b.port));
    let name = manifest.project.name.get_ref();
    let part = manifest
        .project
        .part
        .as_ref()
        .map_or(target.board.part.as_str(), |p| p.get_ref().as_str());
    match target.family.constraint_format {
        ConstraintFormat::Xdc => Generated {
            file_name: format!("{name}.xdc"),
            contents: xdc(name, part, target, &ports),
        },
        ConstraintFormat::Pcf => Generated {
            file_name: format!("{name}.pcf"),
            contents: pcf(name, part, target, &ports),
        },
    }
}

/// Orders `led[2]` before `led[10]`, and a bus after a scalar of the same name.
fn port_order(a: &str, b: &str) -> Ordering {
    let (ab, ai) = split_port_index(a);
    let (bb, bi) = split_port_index(b);
    ab.cmp(bb).then(ai.cmp(&bi)).then(a.cmp(b))
}

fn header(out: &mut String, comment: &str, project: &str, part: &str, target: Target<'_>) {
    let _ = writeln!(
        out,
        "{comment} Generated by BITSTREAM.sh from bitstream.toml. Do not edit; edit bitstream.toml instead."
    );
    let _ = writeln!(out, "{comment} Project: {project}");
    let _ = writeln!(
        out,
        "{comment} Board:   {} ({})",
        target.board.name, target.board.id
    );
    let _ = writeln!(out, "{comment} Part:    {part}");
}

fn is_differential(port: &ResolvedPort, target: Target<'_>) -> bool {
    port.io_standard
        .as_ref()
        .and_then(|s| target.family.io_standard(&s.name))
        .is_some_and(|s| s.differential)
}

fn xdc(project: &str, part: &str, target: Target<'_>, ports: &[&ResolvedPort]) -> String {
    let mut out = String::new();
    header(&mut out, "##", project, part, target);

    if !ports.is_empty() {
        out.push('\n');
    }
    for port in ports {
        let differential = is_differential(port, target);
        let n_pin = port
            .pin_n
            .as_ref()
            .map(|n| n.get_ref().clone())
            .or_else(|| target.device.pin(&port.pin).and_then(|p| p.pair.clone()));
        let legs = match (differential, n_pin) {
            (true, Some(n)) => vec![
                (format!("{}_p", port.port), port.pin.clone()),
                (format!("{}_n", port.port), n),
            ],
            _ => vec![(port.port.clone(), port.pin.clone())],
        };
        for (name, pin) in legs {
            let mut props = vec![format!("PACKAGE_PIN {pin}")];
            if let Some(s) = &port.io_standard {
                props.push(format!("IOSTANDARD {}", s.name));
            }
            match port.pull {
                Some(Pull::Up) => props.push("PULLTYPE PULLUP".into()),
                Some(Pull::Down) => props.push("PULLTYPE PULLDOWN".into()),
                Some(Pull::Keeper) => props.push("PULLTYPE KEEPER".into()),
                Some(Pull::None) | None => {}
            }
            match port.slew {
                Some(Slew::Slow) => props.push("SLEW SLOW".into()),
                Some(Slew::Fast) => props.push("SLEW FAST".into()),
                None => {}
            }
            if let Some(drive) = port.drive {
                props.push(format!("DRIVE {drive}"));
            }
            if let Some(term) = port.diff_term {
                props.push(format!("DIFF_TERM {}", if term { "TRUE" } else { "FALSE" }));
            }
            let _ = writeln!(
                out,
                "set_property -dict {{ {} }} [get_ports {{ {name} }}]",
                props.join(" ")
            );
        }
    }

    let config = &target.board.config;
    if config.config_voltage.is_some() || config.cfgbvs.is_some() {
        out.push_str("\n## Configuration bank\n");
        if let Some(v) = config.config_voltage {
            let _ = writeln!(out, "set_property CONFIG_VOLTAGE {v} [current_design]");
        }
        if let Some(c) = &config.cfgbvs {
            let _ = writeln!(out, "set_property CFGBVS {c} [current_design]");
        }
    }
    out
}

fn pcf(project: &str, part: &str, target: Target<'_>, ports: &[&ResolvedPort]) -> String {
    let mut out = String::new();
    header(&mut out, "#", project, part, target);
    if !ports.is_empty() {
        out.push('\n');
    }
    for port in ports {
        // nextpnr-ice40 only supports pull-ups in PCF; the rules report the rest.
        let pull = if port.pull == Some(Pull::Up) {
            "-pullup yes "
        } else {
            ""
        };
        let _ = writeln!(out, "set_io {pull}{} {}", port.port, port.pin);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn natural_port_order() {
        let mut v = vec!["led[10]", "led[2]", "clk", "led", "btn[0]"];
        v.sort_by(|a, b| port_order(a, b));
        assert_eq!(v, ["btn[0]", "clk", "led", "led[2]", "led[10]"]);
    }
}
