/**
 * toolchain.ts
 * ----------------------------------------------------------------------------
 * Vendor automation. Two things happen here:
 *
 *   1. We generate Tcl scripts from `bitstream.json` into a temporary build
 *      directory (`build/`). Tcl is the only stable surface both Vivado and
 *      Quartus expose for headless flows, so we treat the manifest as input
 *      and Tcl as a pure derived artefact — never hand-edited, regenerated
 *      every build.
 *
 *   2. We invoke vendor CLIs (`vivado`, `quartus_map`/`_fit`/`_asm`,
 *      `quartus_pgm`) via child_process.exec and stream output to a shared
 *      OutputChannel so the user gets live feedback without any vendor GUI
 *      popping up.
 *
 * The Status Bar items in extension.ts are thin wrappers around `build()`
 * and `upload()` below.
 */

import * as vscode from "vscode";
import * as fs from "fs";
import * as path from "path";
import * as cp from "child_process";
import { BitstreamManifest, readManifest } from "./manifest";

const BUILD_DIR = "build";

export class Toolchain {
    private readonly output: vscode.OutputChannel;

    constructor() {
        this.output = vscode.window.createOutputChannel("Bitstream: Toolchain");
    }

    public dispose(): void {
        this.output.dispose();
    }

    /** Resolve the build directory inside the workspace and ensure it exists. */
    private buildDir(workspaceRoot: string): string {
        const dir = path.join(workspaceRoot, BUILD_DIR);
        if (!fs.existsSync(dir)) { fs.mkdirSync(dir, { recursive: true }); }
        return dir;
    }

    // ---- Tcl generators ----------------------------------------------------

    /**
     * Vivado build script: in-memory project (no .xpr written to disk),
     * read sources, set part, synthesize, implement, write bitstream.
     * In-memory keeps the workspace clean — the bitstream is the only
     * artefact we care about persisting.
     */
    public generateVivadoBuildTcl(manifest: BitstreamManifest): string {
        const sources = manifest.source_files.map((f) => `read_verilog -sv {${f}}`).join("\n");
        const xdcs = manifest.constraints.map((f) => `read_xdc {${f}}`).join("\n");
        return [
            `# Auto-generated by Bitstream. Do not edit — regenerated on every build.`,
            `set project_name "${manifest.project_name}"`,
            `set part "${manifest.device}"`,
            ``,
            `# In-memory project (synth/impl without leaving an .xpr on disk).`,
            sources,
            xdcs,
            ``,
            `synth_design -top ${manifest.project_name} -part $part`,
            `opt_design`,
            `place_design`,
            `route_design`,
            ``,
            // Post-route reports the dashboard scrapes — text format so we can
            // parse without spinning up Vivado for the read. -file overwrites,
            // so re-runs don't accumulate stale numbers.
            `report_utilization -file build/${manifest.project_name}_utilization.rpt`,
            `report_timing_summary -file build/${manifest.project_name}_timing.rpt`,
            ``,
            `write_bitstream -force build/${manifest.project_name}.bit`,
            `exit`,
            ``,
        ].join("\n");
    }

    /** Vivado JTAG programming script — opens hw_manager, downloads .bit, closes. */
    public generateVivadoProgramTcl(manifest: BitstreamManifest): string {
        return [
            `# Auto-generated by Bitstream.`,
            `open_hw_manager`,
            `connect_hw_server -allow_non_jtag`,
            `open_hw_target`,
            `set device [lindex [get_hw_devices] 0]`,
            `current_hw_device $device`,
            `set_property PROGRAM.FILE {build/${manifest.project_name}.bit} $device`,
            `program_hw_devices $device`,
            `close_hw_target`,
            `disconnect_hw_server`,
            `close_hw_manager`,
            `exit`,
            ``,
        ].join("\n");
    }

    /**
     * Quartus project Tcl. Unlike Vivado, Quartus's command-line tools
     * (`quartus_map`/`_fit`/`_asm`) operate on an on-disk QSF/QPF pair,
     * so we materialise a minimal project under `quartus_project/`.
     * The directory is gitignored — the manifest stays the source of truth.
     */
    public generateQuartusProjectTcl(manifest: BitstreamManifest): string {
        const sourceCmds = manifest.source_files.map((f) => {
            const ext = path.extname(f).toLowerCase();
            if (ext === ".vhd" || ext === ".vhdl") { return `set_global_assignment -name VHDL_FILE ../${f}`; }
            if (ext === ".sv" || ext === ".svh") { return `set_global_assignment -name SYSTEMVERILOG_FILE ../${f}`; }
            return `set_global_assignment -name VERILOG_FILE ../${f}`;
        }).join("\n");

        const sdcCmds = manifest.constraints
            .filter((f) => f.toLowerCase().endsWith(".sdc"))
            .map((f) => `set_global_assignment -name SDC_FILE ../${f}`)
            .join("\n");

        // Emit pin assignments inline from the manifest so the manifest stays
        // the single source of truth. Accept bare ("A8") or prefixed ("PIN_A8")
        // forms — Quartus requires the PIN_ prefix.
        const pinCmds = Object.entries(manifest.pin_map ?? {})
            .map(([port, pin]) => {
                const norm = pin.startsWith("PIN_") ? pin : `PIN_${pin}`;
                return `set_location_assignment ${norm} -to ${port}`;
            })
            .join("\n");

        return [
            `# Auto-generated by Bitstream.`,
            `package require ::quartus::project`,
            `project_new ${manifest.project_name} -overwrite`,
            `set_global_assignment -name FAMILY "Cyclone V"`,
            `set_global_assignment -name DEVICE ${manifest.device}`,
            `set_global_assignment -name TOP_LEVEL_ENTITY ${manifest.project_name}`,
            `set_global_assignment -name PROJECT_OUTPUT_DIRECTORY output_files`,
            sourceCmds,
            sdcCmds,
            pinCmds,
            `project_close`,
            ``,
        ].join("\n");
    }

    // ---- Execution ---------------------------------------------------------

    /**
     * Run a CLI command, streaming stdout/stderr to the toolchain output
     * channel and rejecting on a non-zero exit. We use spawn (not exec) so
     * output is live, not buffered until the process ends — synthesis runs
     * can take many minutes.
     */
    private run(command: string, args: string[], cwd: string, extraEnv?: NodeJS.ProcessEnv): Promise<void> {
        return new Promise((resolve, reject) => {
            this.output.appendLine(`\n$ ${command} ${args.join(" ")}\n  (cwd: ${cwd})`);
            const env = extraEnv ? { ...process.env, ...extraEnv } : undefined;
            const proc = cp.spawn(command, args, { cwd, shell: false, env });
            proc.stdout.on("data", (d) => this.output.append(d.toString()));
            proc.stderr.on("data", (d) => this.output.append(d.toString()));
            proc.on("error", (err) => reject(new Error(`Failed to spawn ${command}: ${err.message}`)));
            proc.on("close", (code) => {
                if (code === 0) { resolve(); }
                else { reject(new Error(`${command} exited with code ${code}`)); }
            });
        });
    }

    /** Join a configured directory path with a tool name; empty config = system PATH. */
    private resolveTool(configuredDir: string, toolName: string): string {
        if (!configuredDir) { return toolName; }
        return path.join(configuredDir, toolName);
    }

    /**
     * Prepend the Quartus binary directory to LD_LIBRARY_PATH so the dynamic
     * linker can find vendor-private shared libraries (e.g. libdb_asgn.so)
     * that live alongside the executables in the linux64/ folder.
     */
    private quartusEnv(dir: string): NodeJS.ProcessEnv | undefined {
        if (!dir) { return undefined; }
        const existing = process.env.LD_LIBRARY_PATH;
        return { LD_LIBRARY_PATH: existing ? `${dir}:${existing}` : dir };
    }

    /** Build bitstream — vendor-switched on the manifest. */
    public async build(workspaceRoot: string): Promise<void> {
        const manifest = readManifest(workspaceRoot);
        const buildDir = this.buildDir(workspaceRoot);
        this.output.show(true);
        this.output.appendLine(`\n=== Bitstream build for ${manifest.project_name} (${manifest.vendor}/${manifest.device}) ===`);

        if (manifest.vendor === "xilinx") {
            await this.buildVivado(workspaceRoot, manifest, buildDir);
        } else {
            await this.buildQuartus(workspaceRoot, manifest);
        }
        vscode.window.showInformationMessage(`Bitstream: build complete for ${manifest.project_name}.`);
    }

    /** Program the connected board — vendor-switched on the manifest. */
    public async upload(workspaceRoot: string): Promise<void> {
        const manifest = readManifest(workspaceRoot);
        this.output.show(true);
        this.output.appendLine(`\n=== Bitstream upload for ${manifest.project_name} ===`);

        if (manifest.vendor === "xilinx") {
            await this.uploadVivado(workspaceRoot, manifest);
        } else {
            await this.uploadQuartus(workspaceRoot, manifest);
        }
        vscode.window.showInformationMessage(`Bitstream: upload complete for ${manifest.project_name}.`);
    }

    // ---- Xilinx / Vivado ---------------------------------------------------

    private async buildVivado(workspaceRoot: string, manifest: BitstreamManifest, buildDir: string): Promise<void> {
        const tcl = this.generateVivadoBuildTcl(manifest);
        const tclPath = path.join(buildDir, "build.tcl");
        fs.writeFileSync(tclPath, tcl, "utf8");

        const vivado = vscode.workspace.getConfiguration().get<string>("hdlToolchain.vivadoPath", "vivado") || "vivado";
        await this.run(vivado, ["-mode", "batch", "-source", path.relative(workspaceRoot, tclPath)], workspaceRoot);
    }

    private async uploadVivado(workspaceRoot: string, manifest: BitstreamManifest): Promise<void> {
        const buildDir = this.buildDir(workspaceRoot);
        const tcl = this.generateVivadoProgramTcl(manifest);
        const tclPath = path.join(buildDir, "program.tcl");
        fs.writeFileSync(tclPath, tcl, "utf8");

        const vivado = vscode.workspace.getConfiguration().get<string>("hdlToolchain.vivadoPath", "vivado") || "vivado";
        await this.run(vivado, ["-mode", "batch", "-source", path.relative(workspaceRoot, tclPath)], workspaceRoot);
    }

    // ---- Intel / Quartus ---------------------------------------------------

    private async buildQuartus(workspaceRoot: string, manifest: BitstreamManifest): Promise<void> {
        const quartusDir = path.join(workspaceRoot, "quartus_project");
        if (!fs.existsSync(quartusDir)) { fs.mkdirSync(quartusDir, { recursive: true }); }

        // Materialise the QSF/QPF pair via quartus_sh, then run the three
        // pipeline stages individually so a failure (e.g. fit error) bubbles
        // up immediately rather than being swallowed by a wrapper script.
        const projTcl = this.generateQuartusProjectTcl(manifest);
        const projTclPath = path.join(quartusDir, "project.tcl");
        fs.writeFileSync(projTclPath, projTcl, "utf8");

        const cfg = vscode.workspace.getConfiguration();
        const dir = cfg.get<string>("hdlToolchain.quartusPath", "") || "";

        const quartusSh = this.resolveTool(dir, "quartus_sh");
        const quartusMap = this.resolveTool(dir, "quartus_map");
        const quartusFit = this.resolveTool(dir, "quartus_fit");
        const quartusAsm = this.resolveTool(dir, "quartus_asm");
        const quartusSta = this.resolveTool(dir, "quartus_sta");

        const env = this.quartusEnv(dir);
        await this.run(quartusSh, ["-t", "project.tcl"], quartusDir, env);
        await this.run(quartusMap, [manifest.project_name], quartusDir, env);
        await this.run(quartusFit, [manifest.project_name], quartusDir, env);
        await this.run(quartusAsm, [manifest.project_name], quartusDir, env);
        // STA produces the .sta.summary the dashboard reads for Fmax / slack.
        // We run it last so a fit-stage failure still surfaces immediately
        // rather than being shadowed by an STA error on partial output.
        await this.run(quartusSta, [manifest.project_name], quartusDir, env);
    }

    private async uploadQuartus(workspaceRoot: string, manifest: BitstreamManifest): Promise<void> {
        const quartusDir = path.join(workspaceRoot, "quartus_project");
        const cfg = vscode.workspace.getConfiguration();
        const dir = cfg.get<string>("hdlToolchain.quartusPath", "") || "";
        const quartusPgm = this.resolveTool(dir, "quartus_pgm");

        await this.run(
            quartusPgm,
            ["-m", "jtag", "-o", `p;output_files/${manifest.project_name}.sof`],
            quartusDir,
            this.quartusEnv(dir),
        );
    }
}
